# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.product_import_workflow_service:
        class: AppBundle\Service\ImportWorkflow\ProductImportWorkflow
        arguments: ["@doctrine.orm.entity_manager"]
