# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.csv_import_service:
        class: AppBundle\Service\CsvImportService
        arguments: ["@doctrine.orm.entity_manager"]
